name: minitwitter
services:
  load-balancer:
    container_name: load-balancer
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx.conf.ro

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: minitwitter
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data


  minitwitter1:
    image: wotasoy/sensor-api
    container_name: minitwitter1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgressql://postgres:supersecret123@postgres:5432/minitwitter
      SIMULATION: true
    command: bun run src/app.ts
    depends_on:
      - postgres
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data


  minitwitter2:
    image: wotasoy/sensor-api
    container_name: minitwitter2
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgressql://postgres:supersecret123@postgres:5432/minitwitter
      SIMULATION: false
    command: bun run src/app.ts
    depends_on:
      - postgres
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data